[package]
name = "bitwarden-tui"
version = "0.1.0"
authors = ["Lauri Koskela <lk@lkoskela.com>"]
edition = "2018"
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.11"
base64 = "0.11.0"
itertools = "0.8.2"
aes = "0.3.2"
block-modes = "0.3.3"
rsa = "0.5.0"
sha-1 = "0.9.7"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.50"
tokio = { version = "1.2", features = ["full"] }
reqwest = { version = "0.11.1", features = ["json"] }
crossterm = "0.19"
cursive = { version = "0.16", default_features = false, features = ["crossterm-backend"] }
cursive_table_view = "0.13"
log = "0.4"
lazy_static = "1.4"
clipboard = "0.5"
sublime_fuzzy = "0.7"
clap = "3.0.0-beta.2"
directories-next = "2.0.0"
thiserror = "1.0"
anyhow = "1.0"
zeroize = "1.4.1"