name: Main

on:
  push:
    branches: [ main ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  #pull_request:
  #  branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Extract changelog
      shell: bash
      continue-on-error: true  # If parsing the changelog fails, continue with empty changelog
      run: |
        cargo install --verbose --version 0.4.7 parse-changelog
        export VERSION="$GITHUB_REF_NAME"
        parse-changelog CHANGELOG.md "$VERSION" > release-changelog.md
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-changelog.md
        body: ''  # Empty string as fallback

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/wden-rust-env-setup
    
    - name: Run tests
      run: cargo test --verbose --release
    - name: Build
      run: cargo build --verbose --release
    
    - name: Copy binaries to out dir with target name
      shell: bash
      run: |
        mkdir -p out/
        target_triple="$(rustc -vV | sed -n 's|host: ||p')"
        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          cp target/release/wden.exe "out/wden-${target_triple}.exe"
        elif [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
          cp target/release/wden "out/wden-${target_triple}"
        fi

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }} wden binary
        path: out/

    # For tags, create a release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          LICENSE
          out/wden-*