name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      uses: ./.github/actions/wden-rust-env-setup

    - name: cargo check
      run: cargo check --verbose    
    - name: Run tests
      run: cargo test --verbose
