name: Rust

on:
  push:
    branches: [ main ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  #pull_request:
  #  branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Extract changelog
      shell: bash
      continue-on-error: true  # If parsing the changelog fails, continue with empty changelog
      run: |
        cargo install --verbose --version 0.4.7 parse-changelog
        export VERSION="$GITHUB_REF_NAME"
        parse-changelog CHANGELOG.md "$VERSION" > release-changelog.md
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-changelog.md
        body: ''  # Empty string as fallback

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependency libraries
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install -y libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        
    - uses: Swatinem/rust-cache@v1.4.0
    
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} wden binary
        path: |
          target/release/wden
          target/release/wden.exe

    # For tags, copy and zip the binaries to files, and create a release
    - name: Rename binaries
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          cp target/release/wden.exe ./wden-windows-x86_64.exe
        elif [ "${{ matrix.os }}" = "ubuntu-20.04" ]; then
          cp target/release/wden ./wden-linux-x86_64
        fi
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          LICENSE
          wden-*