name: Rust

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependency libraries
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install -y libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        
    - uses: Swatinem/rust-cache@v1.3.0
    
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} wden binary
        path: |
          target/release/wden
          target/release/wden.exe
